server:
  port: 8888
  context-path: /cmfz

  jsp-servlet:
    init-parameters:
      development: true

spring:

  mvc:
    view:
      prefix: /
      suffix: .jsp

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cmfz
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  http:
    multipart:
      max-file-size: 10mb
      max-request-size: 100mb

    encoding:
      charset: UTF-8
      force: true
#mybatis:
  #mapper-locations: classpath:com/sjz/cmfz/dao/*Mapper.xml
mybatis-plus:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
